#!/bin/bash
 # include modpatch function
 . ${include_modpatch}
#### USB-Zubehoer ####
# Remove extra files and directories not required for this product
REMOVELIST_USB="/etc/hotplug /etc/usbclass.tab /etc/usbdevice.tab /usr/share/ctlmgr/libctlusb.so /bin/pause /bin/usbhostchanged \
/sbin/eventadd /sbin/hotplug /sbin/lsusb /sbin/printserv /lib/modules/2.6.13.1-ohio/kernel/drivers/usb \ 
/lib/modules/2.6.13.1-ohio/kernel/drivers/scsi"

for FILE in ${REMOVELIST_USB}; do
	[ -f "${1}${FILE}" ] && echo2 "      ${FILE}"
	[ -f "${1}${FILE}" ] && rm -fdr "${1}${FILE}"
done
$sh_DIR/rmv_usb_menu "$1"
echo2 "   -- Removing directory:"
echo2 "      /usr/www/${HTML}/${avm_Lang}/usb"
rm -rf "$1"/usr/www/${HTML}/${avm_Lang}/usb

exit 0
