#!/bin/bash
. $include_modpatch
echo "-- add tcom link..."
[ ! -L "${1}/etc/default.${CONFIG_PRODUKT}/tcom" ] && ln -s /etc/default.${CONFIG_PRODUKT}/${OEMLINK} "${1}/etc/default.${CONFIG_PRODUKT}/tcom"
webdir="/usr/www"
[ -d ${webdir}/$OEM ] && ln -sf ${webdir}/$OEM ${webdir}/$DIR && echo2 "   added link: $wwwdir/$DIR"
webdir="/usr/www.nas"
[ -d ${webdir}/$OEM ] && ln -sf ${webdir}/$OEM ${webdir}/$DIR && echo2 "   added link: $wwwdir/$DIR"
exit 0

