#!/bin/bash
. $inc_DIR/includefunctions
# IMG_REQ="${1##*/}"
FILE1="$(get_item "$1" "0")"
FILE2="$(get_item "$2" "0")"
AVM__IMG="$FWBASE/${FILE1##*/}"
AVM7270__IMG="$FWBASE/${FILE2##*/}"
if `echo "${1##*/}" | grep -q "$3"` && `echo "${2##*/}" | grep -q "$3"`; then 
 if [ "$SPNUM" == "900" ] || [ "$SPNUM" == "920" ]; then
  [ -f "$HOMEDIR/last_900-920" ] && . "$HOMEDIR/last_900-920"  
  #echo "SPNUM_OLD=\"$SPNUM\"" > "$HOMEDIR/last_900-920"
  #echo "AVM__IMG: $AVM__IMG"
  #echo "AVM7270__IMG: $AVM7270__IMG"
  #echo "SPNUM_OLD: $SPNUM_OLD"
  #echo "SPNUM    : $SPNUM"
  [ "$SPNUM_OLD" ] && [ "$SPNUM" !=  "$SPNUM_OLD" ] && [ "$AVM__IMG" == "$AVM7270__IMG" ] && [ -f "$AVM__IMG" ] && echo "  -- Removed firmware: ${FILE1##*/}" 
  [ "$SPNUM_OLD" ] && [ "$SPNUM" !=  "$SPNUM_OLD" ] && [ "$AVM__IMG" == "$AVM7270__IMG" ] && [ -f "$AVM__IMG" ] && rm -fr "$AVM__IMG"
 fi
fi
exit 0
