#!/bin/bash
. $include_modpatch
rc="rc.S"
[ -f  "${1}/etc/init.d/S01-head" ] && rc="S01-head"
rc="rc.S"
if ! grep -q "echo reenforce urladerversion" "${1}/etc/init.d/$rc" ;then
echo "********************************************************************************"
echo "enforce urlader settings"

mv "${1}/etc/init.d/$rc" "${1}/etc/init.d/rc.S.orig"
sed -i -e 's|#. .bin.sh||' "${1}/etc/init.d/rc.S.orig"
cat > "${1}/etc/init.d/$rc" << EOF
#!/bin/sh
mount -t proc proc /proc
EOF
[ "${ENFORCE_HWREVISION}" == "y" ] && echo 'echo HWRevision '$HWRevision' > /proc/sys/urlader/environment' >> "${1}/etc/init.d/$rc"
echo 'echo ProductID '$CONFIG_PRODUKT' > /proc/sys/urlader/environment' >> "${1}/etc/init.d/$rc"
echo 'echo firmware_version '$OEM' > /proc/sys/urlader/environment' >> "${1}/etc/init.d/$rc"
[ "${ANNEX}"  == "A" ] && echo 'echo kernel_args annex='${ANNEX}' console=ttyS0,38400 > /proc/sys/urlader/environment' >> "${1}/etc/init.d/$rc"
[ "${ANNEX}"  != "A" ] && echo 'echo kernel_args console=ttyS0,38400 > /proc/sys/urlader/environment' >> "${1}/etc/init.d/$rc"
echo 'echo wlan_key '${WLANKEY}' > /proc/sys/urlader/environment' >> "${1}/etc/init.d/$rc"
echo 'echo my_ipaddress 192.168.178.1 > /proc/sys/urlader/environment' >> "${1}/etc/init.d/$rc"
echo 'echo reenforce urladerversion - /proc/sys/urlader'  >> "${1}/etc/init.d/$rc"
if ! grep -q "mount -t proc proc /proc" "${1}/etc/init.d/rc.S.orig" ;then
cat >> "${1}/etc/init.d/$rc" << EOF
umount /proc
EOF
else
 sed -i -e 's|mount -t proc proc .proc||' "${1}/etc/init.d/rc.S.orig"
fi
cat "${1}/etc/init.d/rc.S.orig" >> "${1}/etc/init.d/$rc"
rm -f "${1}/etc/init.d/rc.S.orig"
chmod 755 "${1}/etc/init.d/$rc"
fi
grep -q "echo firmware_version ${OEM} >" "${1}/etc/init.d/$rc" && echo -e " OEM (Branding) set via firmware to:${ECHO_TUERKIS} $OEM $ECHO_END"
grep -q "echo wlan_key ${WLANKEY} >" "${1}/etc/init.d/$rc" && echo -e " default WLAN Key set via firmware to:${ECHO_TUERKIS} $WLANKEY $ECHO_END"
grep -q "echo my_ipaddress 192.168.178.1 >" "${1}/etc/init.d/$rc" && echo -e " my_ipaddress set via firmware to:${ECHO_TUERKIS} 192.168.178.1$ECHO_END"
grep -q "echo ProductID $CONFIG_PRODUKT >" "${1}/etc/init.d/$rc" && echo -e " ProductID set via firmware to:${ECHO_TUERKIS} $CONFIG_PRODUKT$ECHO_END"
grep -q "echo HWRevision $HWRevision >" "${1}/etc/init.d/$rc" && echo -e " HWRevision set via firmware to:${ECHO_TUERKIS} $HWRevision$ECHO_END"
grep -q "kernel_args annex=A console" "${1}/etc/init.d/$rc" && echo -e " ANNEX set via firmware to:${ECHO_TUERKIS} A$ECHO_END"
exit 0
