#!/bin/bash
    echo "-- Replace menu-item assistent..."
for DIR in ${OEMLIST}; do
# if [ "$DIR" = "avme" ] ; then
#  html="$avm_Lang/html"
# else
  html="html"
# fi
    DIRI="usr/www/$DIR/$html/de"
     if [ -d "$1"/$DIRI ]; then
    [ -f "$1/${DIRI}/js/basis.js" ] && sed -i -e 's|jslGoTo("konfig", "home")|jslGoTo("enhsettings", "enhsettings")|' "$1/${DIRI}/js/basis.js"
    fi
done
exit 0
