#!/bin/bash
prompt() {
echo "No image for processing. Press 'ENTER' to return to the calling shell."
while !(read -s); do
    sleep 1
done
exit 1
}
[ -d "$FWBASE" ] || mkdir "$FWBASE"
[ -d "$NEWDIR" ] || mkdir "$NEWDIR"
if [ ! -d "$NEWDIR" ]; then
    echo "Unable to locate/create directory: $NEWDIR"
    sleep 20; exit 1
fi
# Removing privias sources if still in existant
rm -rf "$FBDIR"
rm -rf "$FBDIR_2"
rm -rf "$SPDIR"
rm -rf "$TEMPDIR"
#########################################################################
# Check if images/directories exist or download file
#get tcom source
if [ -n "$SPIMG" ]; then
 fwselect "$SPIMG_PATH" "$FWBASE" "TCOM_IMG" "SPIMG"  "$MIRROR_SPIMG_PATH" "$FILENAME_SPIMG_PATH" "${SPNUM}V"
 [ -z "$SPIMG" ] && prompt
fi
#get sorce 1
if [ "$ORI" != "y" ] || [ "$XCHANGE_KERNEL" = "y" ]; then
 fwselect "$FBIMG_PATH" "$FWBASE" "AVM_IMG" "FBIMG" "$MIRROR_FBIMG_PATH" "$FILENAME_FBIMG_PATH" "$FBMOD"
 [ -z "$FBIMG" ] && prompt
fi
#get sorce 2
if [ -n "$FBIMG_2" ]; then
	fwselect "$FBIMG_2_PATH" "$FWBASE" "SRC2_IMG" "FBIMG_2" "$MIRROR_FBIMG_2_PATH" "$FILENAME_FBIMG_2_PATH" "NO_NUMBER"
	[ -z "$FBIMG_2" ] && prompt
fi
echo "Extracting image files to temporary directories ..."
if [ -n "$SPIMG" ]; then
 echo "-- Unpacking $SPIMG to:"
 echo "      $SPDIR"
 fw_unpack "$FWBASE/$SPIMG" "$SPDIR"
 if [ $? -ne 0 ]; then
	echo "Something went wrong while extracting $SPIMG to $SPDIR"
	rm -rf "$SPDIR"
	rm -rf "$FBDIR"
	rm -rf "$FBDIR_2"
	sleep 20; exit 1
 fi
fi
if [ -n "$FBIMG" ]; then
 echo "-- Unpacking $FBIMG to:"
 echo "      $FBDIR"
 fw_unpack "$FWBASE/$FBIMG" "$FBDIR"
 if [ $? -ne 0 ]; then
	echo "Something went wrong while extracting $FBIMG to $FBDIR"
	rm -rf "$SPDIR"
	rm -rf "$FBDIR"
	rm -rf "$FBDIR_2"
	sleep 20; exit 1
 fi
fi
if [ -n "$FBIMG_2" ]; then
 echo "-- Unpacking $FBIMG_2 to:"
	echo "      $FBDIR_2"
	fw_unpack "$FWBASE/$FBIMG_2" "$FBDIR_2"
	if [ $? -ne 0 ]; then
		echo "Something went wrong while extracting $FBIMG_2 to $FBDIR_2"
		rm -rf "$SPDIR"
		rm -rf "$FBDIR"
		rm -rf "$FBDIR_2"
		sleep 20; exit 1
	fi
fi
    if [ "$VERBOSE" = "-v" ]; then
echo "Images extracted... Press 'ENTER' to continue"
	while !(read -s);do
	    sleep 1
	done
    fi
