#!/bin/bash
#########################################################################
# Check if an error has occured (Size of logfile > 0)                   #
#########################################################################
if [ -s "${HOMEDIR}/${ERR_LOGFILE}" ]; then
	echo "********************************************************************************" >>"${HOMEDIR}/${ERR_LOGFILE}"
	echo "ERROR OCCURED !!! - Push 'Q' to get back." >>"${HOMEDIR}/${ERR_LOGFILE}"
	echo "********************************************************************************" >>"${HOMEDIR}/${ERR_LOGFILE}"
    cat "${HOMEDIR}/${ERR_LOGFILE}" | less
exit 0
fi 
