#!/bin/sh
echo "Setup comlete new Image ----->"
VER="karmic" # this works
VER="oneiric" # problems with udev
#VER="precise" not jet avalabel
#VER="lucid" # also problms with udev

CL_LINIP="192.168.11.150"
(cd /usr/share/debootstrap/scripts; ln -s gutsy $VER)
apt-get install debootstrap
umount /image
#exit
[ -d "/image" ] || mkdir /image
sudo mount -o loop -t ext3  /dev/cobd3 /image

#exit
rm -fr /image/*
sudo debootstrap --verbose --arch i386  $VER /image
mount proc /image/proc/  -t proc
# make dev if not existant
for i in 0 1 2 3 4 5 6 7 8 9
do
  if ! test -f /image/dev/cobd$i ; then
      mknod /image/dev/cobd$i b 117 $i 
  fi
done

cat <<EOF > /image/etc/fstab
# /etc/fstab: static file system information.
#
# <file system>	<mount point>	<type>	<options>		<dump>	<pass>
proc		/proc		proc	defaults		0	0
/dev/cobd0      /               ext3    defaults                1       1
/dev/cobd2      /mnt/suse       ext3    defaults                1       1
/dev/cobd1      none            swap    sw                      0       0
#31              /mnt/and        cofs    defaults                0       0
#/dev/cofs0 /mnt/win cofs uid=1000,gid=1000 0 0
EOF
rm /image/etc/network/interfaces
cat <<EOF >> /image/etc/network/interfaces
# Used by ifup(8) and ifdown(8). See the interfaces(5) manpage or
# /usr/share/doc/ifupdown/examples for more information.

auto lo eth0 eth1 eth2

iface lo inet loopback

iface eth0 inet dhcp

iface eth1 inet static
     address ${CL_LINIP}
     netmask 255.255.255.0
#     gateway 192.168.11.1

iface eth2 inet static
     address 192.168.178.10
     netmask 255.255.0.0
     gateway 192.168.178.1

#iface eth3 inet static
#     address 192.168.2.10
#     netmask 255.255.0.0
#     gateway 192.168.2.1
EOF
cat <<EOF >> /image/etc/apt/sources.list
# Ubuntu supported packages (packages, GPG key: 437D05B5)
deb http://gb.archive.ubuntu.com/ubuntu/ natty main restricted
deb http://gb.archive.ubuntu.com/ubuntu/ natty-updates main restricted
deb http://security.ubuntu.com/ubuntu/ natty-security main restricted

# Ubuntu community supported packages (packages, GPG key: 437D05B5)
deb http://gb.archive.ubuntu.com/ubuntu/ natty universe multiverse
deb http://gbe.archive.ubuntu.com/ubuntu/ natty-updates universe multiverse
deb http://security.ubuntu.com/ubuntu/ natty-security universe multiverse
EOF
sed -i "s/natty/$VER/g" /image/etc/apt/sources.list
cat <<EOF > /image/etc/resolv.conf
# Generated by pump for interface eth0
search local
nameserver 10.0.2.3
EOF
cat <<EOF >> /image/etc/hosts
192.168.11.150	speedLinux
192.168.11.1	windows-host
EOF
#rm -rd /image/lib/modules/*-co-*
rm -rd /image/boot
rm -f  /image/var/log/*.gz
rm -f  /image/var/run/*.pid
rm -f  /image/var/log/wtmp
rm -fr /image/tmp/*
rm -f  /image/src/var/state/apt/lists/ayo.freshrpms.*
rm -f  /image/src/var/cache/apt/*.bin
#set root password
mkdir /image/mnt
mkdir /image/mnt/suse
mkdir /image/mnt/win
mkdir /image/mnt/and
mkdir /image/mnt/samba
cp /etc/shadow /image/etc
cp /passwd.exp /image
cp /setpw /image
cp /setup.sh /image
cp /usr/local/sbin/* /image/usr/local/sbin
cp -fr /etc/andlinux /image/etc
cp /etc/shadow /image/etc
cp /etc/passwd /image/etc
#if [ -e /image/etc/shadow ]; then
#    sed -i -e 's/root:.*/root:\$6\$7lQW4M.N$xcc2IxoOK821I7cRO8rlws/MVgVaForQ9kkoZv0u39rn9FDjJEK.emb3BQRuL8WB2.Wt6DsMAlDkp72Em5vmI1:15278:0:99999:7:::/' "/image/etc/shadow" 
    sed -i -e 's/root:.*/root::12823:0:99999:7:::/' "/image/etc/shadow" 
    echo "---------- removed root password!"
#fi
if [ -e /image/etc/sudoers ]; then
    sed -i -e 's/#.*\%/\%/' "/image/etc/sudoers" 
fi
if [ -e /image/etc/sudoers ] && ! grep -qs "\${NewUser}" /image/etc/sudoers; then
 echo "\${NewUser} ALL=(ALL) ALL" >> "/image/etc/sudoers" 
    echo "---------- added root to /etc/sudoers"
fi
if [ -e /image/usr/bin/startwindowsterminalsession ]; then
    sed -i -e "/sux - /d" "/image/usr/bin/startwindowsterminalsession" 
    echo "sux - root \$(cat /image/etc/winterm)" >> "/image/usr/bin/startwindowsterminalsession"
    echo "---------- added root to /usr/bin/startwindowsterminalsession"
fi
chmod 777 /image/setpw
chmod 777 /image/etc/rc.local
[ -f /image/etc/rc.local ] || echo "#!/bin/sh" >> /image/etc/rc.local
sed -i -e "/network/d" /image/etc/rc.local
grep -q '#!.bin.sh' /image/etc/rc.local || echo "#!/bin/sh" >> /image/etc/rc.local
sed -i -e "/#!.bin.sh/a\
rm -f \/mnt\/and\/firstboot.txt #####\n\
\/setpw #####\n\
if ! [ -d \/var\/run\/network ]; then mkdir -p \/var\/run\/network\/ && \/etc\/init.d\/networking restart;fi\n\
sed -i -e \"\/#####\/d\" \/etc\/rc.local" /image/etc/rc.local
grep -q 'exit' /image/etc/rc.local || echo "exit 0" >> /image/etc/rc.local
exit
# updates must be run after boot, chroot works in some cases
#-------------------------------------------------------------------------------------------------------------------
#chroot /image /usr/bin/apt-get install synaptic
#chroot /image /usr/bin/apt-get remove udev
#exit
chroot /image /usr/bin/apt-get clean
chroot /image /usr/bin/apt-get autoremove
#chroot /image /usr/bin/apt-get update
#chroot /image /usr/bin/apt-get upgrade
#chroot /image /usr/bin/apt-get dist-upgrade

#chroot /image /usr/bin/apt-get install sed
#sed -i 's/natty/oneiric/g' /image/etc/apt/sources.list

#cat /image/etc/apt/sources.list

#chroot /image /usr/bin/apt-get install synaptic
#chroot /image /usr/bin/apt-get upgrade
exit

sudo sed -i 's/oneiric/natty/g' /etc/apt/sources.list
#sudo sed -i 's/gb\./us\./g' /etc/apt/sources.list
#sudo apt-get install update-manager-coresudo debootstrap --verbose --arch i386 jaunty image
sudo apt-get install update-manager-core

#sudo apt-get update && sudo apt-get upgrade
sudo do-release-upgrade -d
#sudo apt-get autoclean

#sudo apt-get install update-manager-core

#2- Edit /etc/update-manager/release-upgrades and set Prompt=normal;

cat /proc/version
lsb_release -a
#echo "issue ----->"
#cat /etc/issue
cat /etc/*-release
sudo rm /etc/issue
#sudo do-release-upgrade -d
exit
wget --quiet http://packages.medibuntu.org/medibuntu-key.gpg -O - | sudo apt-key add -
wget --quiet http://dl.google.com/linux/linux_signing_key.pubtoremove   -O - | sudo apt-key add -
#sudo sed -i 's/natty/karmic/g' /etc/apt/sources.list
#sudo apt-get autoremove
#exit
if grep -q "jaunty" /etc/apt/sources.list; then
sudo sed -i 's/jaunty/karmic/g' /etc/apt/sources.list
sudo apt-get update && sudo apt-get upgrade &&\
sudo apt-get dist-upgrade
#sudo apt-get autoclean
sudo apt-get install update-manager-core
fi
if grep -q "karmic" /etc/apt/sources.list; then
sudo sed -i 's/karmic/natty/g' /etc/apt/sources.list
#sudo apt-get autoclean
sudo apt-get update && sudo apt-get upgrade
fi
if grep -q "natty" /etc/apt/sources.list; then
sudo sed -i 's/natty/oneiric/g' /etc/apt/sources.list
#sudo apt-get -y update && sudo apt-get -y upgrade &&\
#sudo apt-get dist-upgrade &&\

fi
sudo sed -i 's/oneiric/natty/g' /etc/apt/sources.list
#sudo do-release-upgrade -d
sudo apt-get autoclean
update-manager -d

#if grep -q "natty" /etc/apt/sources.list; then
#fi

#wgeet --quiet http://packages.medibuntu.org/medibuntu-key.gpg -O - | sudo apt-key add -
#wget --quiet http://dl.google.com/linux/linux_signing_key.pub -O - | sudo apt-key add -
#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys
#sudo apt-get -y update && 
#sudo apt-get -y install -f cups-ppdc
#cupsddk: Depends: cups-ppdc but it is not installed

#sudo apt-get -y upgrade
#sudo apt-get -y update
#sudo apt-get dist-upgrade -y
#sudo apt-get autoremove -y
#sudo apt-get autoclean -y
#sudo apt-get clean -y

#sudo apt-get install update-manager-core

#sudo apt-get -y update && sudo apt-get -y upgrade

#sudo apt-get autoremove -y
#sudo apt-get autoclean -y
#sudo apt-get clean -y
#sudo apt-get autoclean
echo "End update <-----"
