#!/bin/bash

# andLinux script to start windows terminal session

# wait until drive is mounted
while [ ! -f /mnt/and/settings.txt ]
do
   /bin/sleep 1
done

. /etc/profile

/usr/local/sbin/firstboot.sh

cmd=`cat /etc/andlinux/xsession_cmd`
$cmd
