#!/bin/bash
. $include_modpatch

echo "-- add tcom link..."
[ ! -L "${1}/etc/default.${CONFIG_PRODUKT}/tcom" ] && ln -s /etc/default.${CONFIG_PRODUKT}/${OEMLINK} "${1}/etc/default.${CONFIG_PRODUKT}/tcom"

exit 0

