#!/bin/bash
. $include_modpatch
echo "---> WEBGUI from source 3 (2nd AVM Firmware) is in use!"
for DIR in $OEMLIST; do
 if [ -d "${SRC_2}/usr/www/${DIR}" ]; then
    echo2 "  -- copy /FBDIR2 usr/www/${DIR} -> /FBDIR usr/www/${OEM}"
    echo2 "  -- copy /FBDIR2 usr/www.nas/${DIR} -> /FBDIR usr/www.nas/${OEM}"
    rm -fdr "${SRC}"/usr/www/* #needed 
    rm -fdr "${SRC}"/usr/www.nas/* #needed
    cp -dfpr "${SRC_2}/usr/www/${DIR}" "${SRC}/usr/www/${OEM}"
    cp -dfpr "${SRC_2}/usr/www.nas/${DIR}" "${SRC}/usr/www.nas/${OEM}"
    break
 fi
done
exit 0
