#!/bin/bash
 . $include_modpatch
# copy missing files in OEM dir 
for DIR in ${OEMLIST}; do
 if [ -d "${DST}/etc/default.${DEST_PRODUKT}/${DIR}" ]; then
  for FILE in $(ls "${DST}/etc/default.${DEST_PRODUKT}/${DIR}"); do
    if [ -f "${DST}/etc/default.${DEST_PRODUKT}/${DIR}/${FILE}" ]; then
     if ! [ -f "${SRC}/etc/default.${CONFIG_PRODUKT}/${OEMLINK}/$FILE" ]; then
      cp -fdrp "${DST}/etc/default.${DEST_PRODUKT}"/${DIR}/$FILE "${SRC}/etc/default.${CONFIG_PRODUKT}/${OEMLINK}/$FILE" && echo2 "  copy file from 2nd FW: $FILE"
     fi
    fi 
  done
 fi
done 
