#!/bin/bash
 . $include_modpatch
echo "-- adding GUI switch to set reg_from_outside"
DIRI="$(find ${1}/usr/www/ \( -name fon_config_End.frm  -o -name fon_config.frm -o -name fon_config_IPPhone* -o -name fon1IPPhone* \) -type f -print)"
for file_n in $DIRI; do
    grep -q "id=.uiPostIPPhoneExtRegFromOutside. disabled" "$file_n" || sed -i '/id="uiPostIPPhoneExtNumber"/ a<Input type="hidden" name="voipextension:settings/extension<? echo $var:DeviceIpPhonePort ?>/reg_from_outside" value="" id="uiPostIPPhoneExtRegFromOutside" disabled>' "$file_n"
    grep -q "CopyValue. .uiPostIPPhoneExtRegFromOutside., .uiIPPhoneExtRegFromOutside" "$file_n" || sed -i '/jslEnable("uiPostIPPhoneExtNumber")/ ajslCopyValue( "uiPostIPPhoneExtRegFromOutside", "uiIPPhoneExtRegFromOutside"); jslEnable("uiPostIPPhoneExtRegFromOutside");' "$file_n"
    grep -q "var:IPPhoneExtRegFromOutside" "$file_n" || sed -i '/id="uiShowOutgoingMsn"/ i<? if eq "$var:TechType" "IPPHONE" ` \n<tr><td class="c1"><span >reg_from_outside</span></td>\n<td class="c2">\n<? if eq "$var:IPPhoneExtRegFromOutside" "1"\n`\nyes\n` `\nno\n` ?>\n</td></tr>\n` ?>' "$file_n"
    grep -q "id=.uiIPPhoneExtRegFromOutside" "$file_n" || sed -i '/id="uiIPPhoneExtNumber"/ a<input type="hidden" name="var:IPPhoneExtRegFromOutside" value="<? echo $var:IPPhoneExtRegFromOutside ?>" id="uiIPPhoneExtRegFromOutside">' "$file_n"
    grep -q "uiIPPhoneExtRegFromOutside" "$file_n" || sed -i '/jslCopyValue( "uiIPPhoneExtNumber", "uiDevicePort")/ ajslSetValue( "uiIPPhoneExtRegFromOutside", (jslGetChecked("uiRegFromOutside"))? "1" : "0");' "$file_n"
    grep -q "id=.uiRegFromOutside" "$file_n" || sed -i '/<\/table>/ i<tr style="padding-top:15px;padding-bottom:15px;">\n<td style="width: 190px; height:30px;">Registrierung v. Extern</td>\n<td><input type="checkbox" name="reg_from_outside" id="uiRegFromOutside"></td>\n</tr>' "$file_n"
    grep -q "id=.uiPostIPPhoneRegFromOutside" "$file_n" || sed -i '/id="uiPostIPPhonePasswd"/ a<Input type="hidden" name="voipextension:settings/extension<? echo $var:DeviceIpPhonePort ?>/reg_from_outside" value="<? query voipextension:settings/extension<? echo $var:DeviceIpPhonePort ?>/reg_from_outside ?>" id="uiPostIPPhoneRegFromOutside">' "$file_n"
    grep -q "uiPostIPPhoneRegFromOutside., .uiRegFromOutside" "$file_n" || sed -i '/function uiDoOnLoad()/,/function uiDoCancel()/ {s%jslDisplay("uiIP_General",true);%&\njslGetCheckValue( "uiRegFromOutside", "uiPostIPPhoneRegFromOutside");% 1 ; s%if (jslGetValue("uiViewPassword") \!="\*\*\*\*")%jslSetCheckValue( "uiPostIPPhoneRegFromOutside", "uiRegFromOutside");\n&%1}' "$file_n"
    grep -q "id=.uiRegFromOutside" "$file_n" || sed -i '/id="uiViewPassword"/ a</tr>\n<tr style="padding-top:15px;padding-bottom:15px;">\n<td style="width: 190px; height:30px;">Registrierung v. Extern</td>\n<td><input type="checkbox" name="reg_from_outside" id="uiRegFromOutside" value="0")"></td>' "$file_n"
    grep -q "RegFromOutside" "$file_n" && echo2 " -- added Reg From Outside to file: ${file_n##*/}"
done
exit 0
