#!/bin/bash
echo "-- add support menu-item..."
for DIR in $2; do
 html="html"
 DIRI="usr/www/$DIR/$html/de"
 #patch download url and add menuitem support
 if [ "$ADD_SUPPORT" == "y" ]; then
  if [ -d "$1"/$DIRI ]; then
    # workaround freetz
    if `cat "$1/${DIRI}/menus/menu2_homehome.html" | grep -q 'freetz_status' `; then 
#     sed -i -e "/freetz_status/i \
#<li class=\"LMenuitemTop\"><img src=\"<? echo \$var:pfeil ?>\"> <a href=\"..\/html\/support.html\" target=\"_blank\">Support<\/a><\/li>" "$1/${DIRI}/menus/menu2_konfig.html"
     sed -i -e "/freetz_status/i \
<li class=\"LMenuitemTop\"><img src=\"<? echo \$var:aktivpfeil ?>\"> <a href=\"..\/html\/support.html\" target=\"_blank\">Support<\/a><\/li>" "$1/${DIRI}/menus/menu2_homehome.html"
    else
#     sed -i -e "/LMenubottom/i \
#<li class=\"LMenuitemTop\"><img src=\"<? echo \$var:pfeil ?>\"> <a href=\"..\/html\/support.html\" target=\"_blank\">Support<\/a><\/li>" "$1/${DIRI}/menus/menu2_konfig.html"
     sed -i -e "/LMenubottom/i \
<li class=\"LMenuitemTop\"><img src=\"<? echo \$var:aktivpfeil ?>\"> <a href=\"..\/html\/support.html\" target=\"_blank\">Support<\/a><\/li>" "$1/${DIRI}/menus/menu2_homehome.html"
    fi
  fi
 #17671 -->
 [ -f "$1/usr/www/$DIR/menus/menu_data.lua" ] && sed -i -e "/assis.home.lua/i \
page = \"\/html\/support.html\",\n\
target = \"_blank\",\n\
text = \"Support\",\n\
menu = \"main\",\n\
subpages = {}\n\
}\n\
-------------------------------------------------------------------------------\n\
menu.add_item{" "$1/usr/www/$DIR/menus/menu_data.lua" && \
 grep -q "support.html" "$1/usr/www/$DIR/menus/menu_data.lua" && echo "-- support menue added to: /usr/www/$DIR/menus/menu_data.lua"
 fi #<-- Support menu
# <-- 17671
done
exit 0


