#!/bin/bash
    echo "-- Add support menu-item..."
for DIR in $2; do
# if [ "$DIR" = "avme" ] ; then
#  html="$avm_Lang/html"
# else
  html="html"
# fi
    DIRI="usr/www/$DIR/$html/de"
  if [ -d "$1"/$DIRI ]; then
 [ -f "$1/${DIRI}/usb/aura.html" ] && sed -i -e 's|TextInstallationErforderlich ?>||' "$1/${DIRI}/menus/menu2_konfig.html"
    # workaround freetz
    if `cat "$1/${DIRI}/menus/menu2_homehome.html" | grep -q 'freetz_status' `; then 
#     sed -i -e "/freetz_status/i \
#<li class=\"LMenuitemTop\"><img src=\"<? echo \$var:pfeil ?>\"> <a href=\"..\/html\/support.html\" target=\"_blank\">Support<\/a><\/li>" "$1/${DIRI}/menus/menu2_konfig.html"
     sed -i -e "/freetz_status/i \
<li class=\"LMenuitemTop\"><img src=\"<? echo \$var:aktivpfeil ?>\"> <a href=\"..\/html\/support.html\" target=\"_blank\">Support<\/a><\/li>" "$1/${DIRI}/menus/menu2_homehome.html"
    else
#     sed -i -e "/LMenubottom/i \
#<li class=\"LMenuitemTop\"><img src=\"<? echo \$var:pfeil ?>\"> <a href=\"..\/html\/support.html\" target=\"_blank\">Support<\/a><\/li>" "$1/${DIRI}/menus/menu2_konfig.html"
     sed -i -e "/LMenubottom/i \
<li class=\"LMenuitemTop\"><img src=\"<? echo \$var:aktivpfeil ?>\"> <a href=\"..\/html\/support.html\" target=\"_blank\">Support<\/a><\/li>" "$1/${DIRI}/menus/menu2_homehome.html"
    fi
  fi
done
exit 0


