#!/bin/sh
echo "Update ----->"
if [ -e /etc/SuSE-release -a -x /usr/bin/zypper ] ; then
	echo "openSUSE detected"
	sudo zypper --non-interactive up
	sudo zypper --non-interactive install subversion gcc gcc-c++ binutils autoconf automake libtool make bzip2 ncurses-devel zlib-devel flex bison patch texinfo gettext-tools jam pkg-config jikes fastjar perl ruby gawk python $EXTRAPKG realpath
else
	sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade &&\
	sudo apt-get -y install gcc g++ binutils autoconf automake automake1.9
	sudo apt-get -y update && sudo apt-get -y upgrade &&\
	sudo apt-get -y install libtool make libncurses5-dev zlib1g-dev flex bison patch texinfo
	sudo apt-get -y update && sudo apt-get -y upgrade &&\
	sudo apt-get -y install tofrodos gettext jam pkg-config jikes fastjar realpath perl
	sudo apt-get -y update && sudo apt-get -y upgrade &&\
	sudo apt-get -y install libstring-crc32-perl ruby ruby1.8 gawk python subversion bzip2 $EXTRAPKG lynx
fi
echo "End update <-----"
