#!/bin/bash
#KernelVersion="2.6.19.2"
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# only executed if productname is changed
if [ ! -e "${SRC}"/etc/default.${CONFIG_PRODUKT} ]; then
echo -e "\033[1m${SORCE_PRODUKT}  --->   ${CONFIG_PRODUKT}\033[0m "
 echo2 "  -- move contents of OEM directory:"
 echo2 "      move /etc/default.${SORCE_PRODUKT} --> /etc/default.${CONFIG_PRODUKT}"
    mkdir -m 755 "${SRC}/etc/default.${CONFIG_PRODUKT}"
   "$TAR" -c -C "${SRC}/etc/default.${SORCE_PRODUKT}" . | "$TAR" -x -C "${SRC}/etc/default.${CONFIG_PRODUKT}"
    rm -fdr "${SRC}"/etc/default.${SORCE_PRODUKT}
fi
#Attention! Vinax uses aditional /dev/vinax device entrys the are generateed via /tools/device_table.txt (makedevice option)
# cp -fdrp "${DST}"/dev --target-directory="${SRC}" #this copy is only usable if run as root
 # "vinax_fw_adsl.bin" "vinax_fw_vdsl.bin"
 #remove 7270 DSL
# rm -fdr "${SRC}"/lib/modules/dsp_ur8
# rm -fdr "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/dsl
 # "vinax_driver"
# [ -d "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax ] || mkdir "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax
# cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax
# cp -fdrp "${DST}"/lib/modules/$KernelVersion/modules.symbols --target-directory="${SRC}"/lib/modules/$KernelVersion
# cp -fdrp "${DST}"/lib/modules/$KernelVersion/modules.alias --target-directory="${SRC}"/lib/modules/$KernelVersion
# cp -u "${DST}"/usr/sbin/* --target-directory="${SRC}"/usr/sbin 2> /dev/null
# cp -fdrp "${DST}"/lib/modules/vinax* --target-directory="${SRC}"/lib/modules &&\
 echo "-- DSL driver was taken from the original base firmware"
# [ -f "${SRC}"/usr/share/ctlmgr/libvdsl.so ] || cp -fdrp "${DST}"/usr/share/ctlmgr/libvdsl.so --target-directory="${SRC}"/usr/share/ctlmgr
# [ -f "${SRC}"/usr/share/ctlmgr/libtr064.so ] || cp -fdrp "${DST}"/usr/share/ctlmgr/libtr064.so --target-directory=${SRC}/usr/share/ctlmgr

##VINAX DRV
#[ "${FORCE_VINAX_DRV}" = "y" ] && cp -fdrp ${HOMEDIR}/addon/tmp/modules/vinax/drv_vinax.ko --target-directory="${SRC}/lib/modules/$KernelVersion/kernel/drivers/vinax" &&\
#echo "-- PPPoA compatible VINAX DSL driver is in use!"
#[ "${FORCE_KDSLD_DRV}" = "y" ] && cp -fdrp ${HOMEDIR}/addon/tmp/modules/dsld/kdsldmod.ko --target-directory="${SRC}/lib/modules/$KernelVersion/kernel/drivers/dsld" &&\
#echo "-- PPPoA compatible KDSLDMOD driver is in use!"#

#[ "${FORCE_VINAX_DRV_77}" = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko --target-directory="${SRC}/lib/modules/$KernelVersion/kernel/drivers/vinax" &&\
#echo "-- compatible VINAX DSL driver is in use!"
#[ "${FORCE_KDSLD_DRV_77}" = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/dsld/kdsldmod.ko --target-directory="${SRC}/lib/modules/$KernelVersion/kernel/drivers/dsld" &&\
#echo "-- compatible KDSLDMOD driver is in use!"

#DECT
rm -rf "${SRC}"/lib/modules/*_488.hex
if [ "${SAVE_SRC2_DECTDRIVER}" = "y" ]; then
    mkdir -p ./addon/tmp/W920/squashfs-root/lib/modules
    cp -fdrp "${SRC_2}"/lib/modules/dectfw_firstlevel.hex --target-directory=./addon/tmp/W920/squashfs-root/lib/modules &&\
    cp -fdrp "${SRC_2}"/lib/modules/dectfw_secondlevel.hex --target-directory=./addon/tmp/W920/squashfs-root/lib/modules &&\
    echo "-- 2nd AVM Firmware DECT driver saved to: ./addon/tmp/W920"
fi
[ "${FORCE_DST_DECTDRIVER}" = "y" ] && cp -fdrp "${DST}"/lib/modules/dectfw_firstlevel.hex --target-directory="${SRC}"/lib/modules &&\
cp -fdrp "${DST}"/lib/modules/dectfw_secondlevel.hex --target-directory="${SRC}"/lib/modules &&\
echo "-- DECT driver was taken from 1st source (base firmware)."
[ "${FORCE_SRC2_DECTDRIVER}" = "y" ] && cp -fdrp "${SRC_2}"/lib/modules/dectfw_firstlevel.hex --target-directory="${SRC}"/lib/modules &&\
cp -fdrp "${SRC_2}"/lib/modules/dectfw_secondlevel.hex --target-directory="${SRC}"/lib/modules &&\
echo "-- DECT driver was taken from 2nd AVM source."
[ "${FORCE_OWN_DECTDRIVER}" = "y" ] && cp -fdrp ./addon/tmp/W920/squashfs-root/lib/modules/dectfw_firstlevel.hex --target-directory="${SRC}"/lib/modules &&\
cp -fdrp ./addon/tmp/W920/squashfs-root/lib/modules/dectfw_secondlevel.hex --target-directory="${SRC}"/lib/modules &&\
echo "-- DECT driver was taken from local directory ./addon/tmp/W920"
if `cat "${SRC}/etc/init.d/rc.S" | grep -q '_488.hex' ` && ! [ -f "${SRC}"/lib/modules/dectfw_firstlevel.hex ]; then
 echo "You must use dect driver form 2nd AVM source or one that was saved before" && sleep 10 && exit 1
fi

#DSL skripts--->
#include vdsl skript

#copy VDSL Skript
#cp -fdpr  "${DST}"/etc/init.d/rc.vdsl.sh  --target-directory="${SRC}"/etc/init.d
#include vdsl skript
#sed -i -e 's|/etc/init.d/rc.dsl.sh start|\. /etc/init.d/rc.vdsl.sh|' "${SRC}/etc/init.d/E46-net"

##diffence in rc.dsl.sh  
#sed -i -e 's|dsl_ur8|tiatm|' "${SRC}/etc/init.d/rc.dsl.sh"
#sed -i -e '/modprobe tiatm/a\
#echo "MODE = vdsl" > \/dev\/avm_power' "${SRC}/etc/init.d/rc.dsl.sh"

##disabel watchdog
#sed -i -e 's|echo init-start 480 >/dev/watchdog||' "${SRC}/etc/init.d/S05-watchdog"

#<---DSL skripts
#tests 
#remove FON3 menus
#[ ${REMOVE_MENU_ITEM} = "y" ] && $sh_DIR/rmv_menus.sh "${SRC}" "${FBMOD}"
# add missing gifs
#### piglet init file
#echo AVM_PRINTK >/dev/debug
#cat /dev/debug &
#modprobe Piglet_noemif piglet_dectmode=0x100 dect_secondlevelfile=/lib/modules/dectfw_secondlevel.hex dect_firstlevelfile=/lib/modules/dectfw_firstlevel.hex 
#piglet_bitfile=/lib/modules/microvoip_isdn_top.bit${HWRevision_BitFileCount} piglet_use_pll3_clk=1

sed -i -e 's|piglet_dectmode=0x100 ||' "${SRC}/etc/init.d/S11-piglet"

#Attention! Vinax uses aditional /dev/vinax device entrys the are generateed via /tools/device_table.txt (makedevice option)

## Fritz_Box_7570 - hw920
## DECT-Anlage braucht den 96 MHz Takt NICHT (250E): 'piglet_use_pll3_clk=1' entfällt, da fpga den 96 MHz Takt aus dem DECT Takt selbst erzeugt.
##########################################################################################
#sed -i -e 's|piglet_use_pll3_clk=1|piglet_enable_button=3|' "${SRC}/etc/init.d/S11-piglet"
sed -i -e 's|piglet_use_pll3_clk=1||' "${SRC}/etc/init.d/S11-piglet"


#v3 dect fix
sed -i -e 's|_488.hex|.hex|g' "${SRC}/etc/init.d/S11-piglet"
##xilix W920 driver must be for the hardware in use
rm -f "${SRC}"/lib/modules/microvoip_isdn_top.bit
rm -f "${SRC}"/lib/modules/bitfile.bit
sed -i -e 's|bitfile.bit|microvoip_isdn_top.bit|' "${SRC}/etc/init.d/S11-piglet" 
sed -i -e 's|microvoip_isdn.bit|microvoip_isdn_top.bit|' "${SRC}/etc/init.d/S11-piglet" 
# 7240
rm -f "${SRC}"/lib/modules/bitfile_pots.bit 
rm -f "${SRC}"/lib/modules/bitfile_isdn.bit 
sed -i -e 's|bitfile_isdn.bit|microvoip_isdn_top.bit|' "${SRC}/etc/init.d/S11-piglet" 
[ -e "${DST}"/lib/modules/microvoip_isdn_top.bit ] && cp -fdrp "${DST}"/lib/modules/microvoip_isdn_top.bit --target-directory="${SRC}"/lib/modules &&\
echo "-- Xilinx bitfile was taken from the original base firmware"
[ -e "${DST}"/lib/modules/bitfile.bit ] && cp -fdrp "${DST}"/lib/modules/bitfile.bit "${SRC}"/lib/modules/microvoip_isdn_top.bit &&\
echo "-- Xilinx bitfile was taken from the original base firmware"
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo "-- Matching Versions: $AVM_VERSION-$AVM_SUBVERSION - $TCOM_VERSION-$TCOM_SUBVERSION"
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# set led definition 
# 920
 
##---$sh_DIR/patch_config_rc.conf.sh "${SRC}" "${DST}" 920

#VDSL would not start if wrong HWrevision is in use, so it only can be set in ATA mod
#But pluginsupport needs AVM HWrevision to setup the download URL for plugins 
#woarkaround v1 Firmware 
##echo "FBIMG: $FBIMG"
#echo $FBIMG | grep -q "v1" && \
#[ "$FBHWRevision" == "139" ] && export FBHWRevision="122"
#if [ "${ENFORCE_HWREVISION}" != "y" ]; then
#echo "-- download plugin URL uses Hardware Revision Number: $FBHWRevision"
##workaround for HWRevision
#if [ -f "${SRC}/sbin/start_plugin.sh" ]; then
#sed -i -e "/url=\"\`\/sbin\/pluginurl\`\"/i\
#	export HWRevision=\"$FBHWRevision\"" "${SRC}/sbin/start_plugin.sh"
#sed -i -e "/url=\"\`\/sbin\/pluginurl\`\"/a\
#	export HWRevision=\"$HWID\"" "${SRC}/sbin/start_plugin.sh"
#fi
#else
# sed -i -e "s|VINAX_IRQ=10|VINAX_IRQ=9|" "${SRC}/etc/init.d/rc.vdsl.sh"
#fi

sed -i -e "s|HWRevision=..|HWRevision=${FBHWRevision}|" "${SRC}/etc/init.d/rc.conf"

#copy second source internet dsl menue
#[ ${USE_SOURCE2_DSLMNUE} = "y" ] && $sh2_DIR/copy_dsl_tab_pages_SRC2 "${SRC}" "${SRC_2}"
#echo2 "-- New WEB GUI will be modified"
#use scond source web GUI
#[ ${USE_SOURCE2_WEBMNUE} = "y" ] && $sh2_DIR/copy_www_SRC2 "${SRC}" "${SRC_2}"
#Add buchsend button to fon bookpage
#[ "${ADD_PHONESEND}" = "y" ] && $sh_DIR/patch_fonbuch.sh "${SRC}"
## skripts for startig ftp on USB
#if [ ${ATA_ONLY} = "y" ]; then
#remove ADSL
#    sed -i -e 's|/etc/init.d/rc.dsl.sh start||' "${SRC}/etc/init.d/rc.S" 
#    sed -i -e 's|. /etc/init.d/rc.vdsl.sh||' "${SRC}/etc/init.d/rc.S" 
#    rm -fdr "${SRC}"/lib/modules/dsp_ur8
#fi
#wrap dsld and ar7cfg.lib
#[ "${WRAP_DSLD}" = "y" ] && . $sh_DIR/wrap_dsld.sh
# remove SNR part - rename Tab, if not Multiannex remove SNR tab
echo "********************************************************************************"