#!/bin/sh
if test -x /sbin/ftpd; then
 ENABLED=`echo usbhost.ftp_server_enabled|ar7cfgctl -s`
 if [ "$ENABLED" != "no" ] ; then
  ftpd -D -q -t 120 -m 15 -h "$CONFIG_PRODUKT_NAME" &
 fi
fi

#while !(read -s);do
#	sleep 1
#done

exit 0