#! /bin/sh
#Copy this script into '/etc/init.d/launcher' and then run 'update-rc.d launcher defaults'. This will make sure the script comes up at run time.
### BEGIN INIT INFO
# Provides:      launcher.pl
# Required-Start:   
# Required-Stop:
# Default-Start:            2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:    launcher perl script
### END INIT INFO

LAUNCHER_SCR=/usr/local/sbin/launcher.pl
set -e
export DISPLAY=192.168.11.1:0.0
export SHELL=/bin/bash
export HOME=~/

if  [ ! -r ~/.bashrc ] ; then
export TERM=linux
export EDITOR=vi
else
. ~/.bashrc
fi;

case "$1" in
start)
$LAUNCHER_SCR
;;
stop)
pkill -TERM launcher.pl
;;
*)
echo "Usage: start|stop"
exit 1
;;
esac
exit 0
				    