#!/bin/bash
echo "--------------------------------------------------------------------------------"
HOMEDIR=$(pwd)
export FWORIGDIR="Firmware.orig"
export FWBASE="$HOMEDIR/$FWORIGDIR"
export FWNEWDIR="Firmware.new"
export NEWDIR="$HOMEDIR/$FWNEWDIR"
FBMOD="7170"
SPNUM="900"
NEWIMG="fw_C_Speedport_900_34.04.57-0_Fritz_Box_DECT_W900V_29.04.76-0-sp2fr-09.10.14-r-593M-946_OEM-avm_de.image"
#above settings are not in use if ./incl_var is included
. ./incl_var
#-------------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------------
RECOVERIMG7141="ftp://ftp.avm.de/fritz.box/fritzbox.fon_wlan_7141/x_misc/deutsch/fritz.box_fon_wlan_7141.04.76.recover-image.exe"
RECOVERIMG7113="ftp://ftp.avm.de/fritz.box/fritzbox.fon_wlan_7113/x_misc/deutsch/FRITZ.Box_Fon_WLAN_7113.04.67.recover-image.exe"
RECOVERIMG7150="ftp://ftp.avm.de/fritz.box/fritzfon.7150/x_misc/FRITZ.Fon_7150.AnnexB.04.71.recover-image.exe"
RECOVERIMG7170="ftp://ftp.avm.de/fritz.box/fritzbox.fon_wlan_7170/x_misc/deutsch/FRITZ.Box_Fon_WLAN_7170.04.76.recover-image.exe"
RECOVERIMG7270="ftp://ftp.avm.de/fritz.box/fritzbox.fon_wlan_7270/x_misc/english/FRITZ.Box_Fon_WLAN_7270_16.AnnexB.en-de-es-it-fr.04.76.recover-image.exe"
#-------------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------------
#for all newer 4mb boxes
[ "${FBMOD}" == "7140" ] && R_IMG="$RECOVERIMG7141"
#for a Sinus500 
[ "${FBMOD}" == "7150" ] && R_IMG="$RECOVERIMG7150"
#for all newer 8mb boxes
[ "${FBMOD}" == "7170" ] && R_IMG="$RECOVERIMG7170"
#for all 16MB boxes
[ "${FBMOD}" == "7270" ] && R_IMG="$RECOVERIMG7270"
#-------------------------------------------------------------------------------------------------
input_recover_file="$FWBASE/$(echo $R_IMG | sed -e "s/.*\///")"
#echo "R_IMG: $R_IMG"
#echo "input_recover_file: $input_recover_file"
[ -f $input_recover_file ] || wget -P "$FWBASE" "$R_IMG"
#-------------------------------------------------------------------------------------------------
kernel_dir="$NEWDIR"
mkdir -p "$kernel_dir"
output_dir="$(basename "$input_recover_file" | sed -r 's/(.*)\.[^\.]*/\1/')"
mkdir -p "$output_dir"
#$HOMEDIR/recoversubscripts/split_image $HOMEDIR $NEWIMG $kernel_dir
## the same as split_image but with tar
$HOMEDIR/recoversubscripts/extract_kernel.image $HOMEDIR $NEWIMG $kernel_dir
if ! [ -f "$kernel_dir/kernel.image" ];then
    echo "New kernel.image is missing!"
    sleep 20
    exit 1
fi
if ! [ -f "$input_recover_file" ];then
    echo "recover.exe file is missing!"
    sleep 20
    exit 1
fi
$HOMEDIR/recoversubscripts/split_recover $HOMEDIR $input_recover_file $output_dir
new_recover_file="$kernel_dir/$(echo "$NEWIMG" | sed -r 's/.image//' | sed -r 's/fw_//' | sed -r 's/C_//').exe"
#new_recover_file="$kernel_dir/Speedport_W${SPNUM}V.recover-image.exe"
echo "--------------------------------------------------------------------------------"
if [ "${SPNUM}" != "7570" ]; then
 sed -i -e "s|FRITZ!Box Fon WLAN 7170|FRITZ!Box Speedp. W${SPNUM}V|g" "$output_dir/exe_end"
 sed -i -e "s|FRITZ!Box Fon WLAN 7170|FRITZ!Box Speedp. W${SPNUM}V|g" "$output_dir/recover.exe"
 sed -i -e "s|FRITZ!Box Fon WLAN 7270|FRITZ!Box Speedp. W${SPNUM}V|g" "$output_dir/recover.exe"
else
 sed -i -e "s|FRITZ!Box Fon WLAN 7270|FRITZ!Box Fon WLAN 7570|g" "$output_dir/recover.exe"
fi
#0x1a249
sed -i -e 's|\x0F\x85\xFA\x01\x00\x00\x8D\x85|\x90\x90\x90\x90\x90\x90\x8D\x85|' "$output_dir/recover.exe"
#0x1a25e
sed -i -e 's|\x0F\x85\x26\x02\x00\x00\x39\x9D|\x90\x90\x90\x90\x90\x90\x39\x9D|' "$output_dir/recover.exe"
#0x1a684
sed -i -e 's|\x74\x59\x83\xFF\xFF\x89\xBD|\xEB\x59\x83\xFF\xFF\x89\xBD|' "$output_dir/recover.exe"
#0x18520
sed -i -e 's|\xC4\x0C\x85\xC0\x74\x4A|\xC4\x0C\x85\xC0\xEB\x4A|' "$output_dir/recover.exe"
#0x1a310
#sed -i -e 's|\x73\x06\x89\x1D\x50\xB6\x8F\x00|\x73\x00\x90\x90\x50\xB6\x8F\x00|' "$output_dir/recover.exe"
#0x1a308
#sed -i -e 's|\x72\x0E\x81\xFF\xE8\x03\x00\x00|\x72\x08\x81\xFF\xE8\x03\x00\x00|' "$output_dir/recover.exe"
rplbytes="90 90 90 90 90 90 8d 85"
[ "$rplbytes" != "$(tools/hexgrep "$rplbytes" "$output_dir/recover.exe" | sed 's/.*://')" ] && echo "-- Firmware version check remove error!" && checkerror="y"
rplbytes="90 90 90 90 90 90 39 9d"
[ "$rplbytes" != "$(tools/hexgrep "$rplbytes" "$output_dir/recover.exe" | sed 's/.*://')" ] && echo "-- OEM check remove error" && checkerror="y"
rplbytes="eb 59 83 ff ff 89 bd"
[ "$rplbytes" != "$(tools/hexgrep "$rplbytes" "$output_dir/recover.exe" | sed 's/.*://')" ] && echo "-- Kernel check remove error" && checkerror="y"
rplbytes="c4 0c 85 c0 eb 4a"
[ "$rplbytes" != "$(tools/hexgrep "$rplbytes" "$output_dir/recover.exe" | sed 's/.*://')" ] && echo "-- CRC check remove error" && checkerror="y"
#rplbytes="73 00 90 90 50 b6 8f 00"
#[ "$rplbytes" != "$(tools/hexgrep "$rplbytes" "$output_dir/recover.exe" | sed 's/.*://')" ] && echo "-- Urloader update remove error" && checkerror="y"
#rplbytes="72 08 81 ff e8 03 00 00"
#[ "$rplbytes" != "$(tools/hexgrep "$rplbytes" "$output_dir/recover.exe" | sed 's/.*://')" ] && echo "-- Urloader2 update remove error!" && checkerror="y"
act_size=`ls -l "$output_dir/kernel.image" | sed -e 's/[^0-9]/#/g' | sed -e 's/#\+[0-9]\+#\+\([0-9]\+\).*/\1/'`
new_act_size=`ls -l "$kernel_dir/kernel.image" | sed -e 's/[^0-9]/#/g' | sed -e 's/#\+[0-9]\+#\+\([0-9]\+\).*/\1/'`
act_diff=$((act_size - new_act_size))
#echo "original size= $act_size, new size= $new_act_size, difference= $act_diff" 
error_size=$((new_act_size - act_size))
[ $act_size -lt $new_act_size ] && echo "ERROR!! New kernel.image does not fit into recover firmware!" && checkerror="y"
dd if=/dev/zero bs=1 count=$act_diff >$output_dir/zerro.image 2> /dev/null
#echo "concat all parts ..."
cat $output_dir/recover.exe >$new_recover_file
cat $kernel_dir/kernel.image >>$new_recover_file
cat $output_dir/zerro.image >>$new_recover_file
cat $output_dir/exe_mid >>$new_recover_file
cat $output_dir/urlader.image >>$new_recover_file
cat $output_dir/exe_end >>$new_recover_file
if  ! `cat "$new_recover_file" | grep -q "FRITZ!Box Speedp. W${SPNUM}V"`; then
 echo "-- Text not changed to: FRITZ!Box Speedp. W${SPNUM}V"
fi
chmod -x $new_recover_file
act_size=`ls -l "$input_recover_file" | sed -e 's/[^0-9]/#/g' | sed -e 's/#\+[0-9]\+#\+\([0-9]\+\).*/\1/'`
new_act_size=`ls -l "$new_recover_file" | sed -e 's/[^0-9]/#/g' | sed -e 's/#\+[0-9]\+#\+\([0-9]\+\).*/\1/'`
#echo "actual size= $act_size,  new actual size= $new_act_size" 
[ $act_size -eq $new_act_size ] || echo "ERROR! Reduce size of kernel.image by: $error_size" 
[ $act_size -eq $new_act_size ] && echo "New Recover: $new_recover_file" 
if [ "$checkerror" == "y" ]; then
    rm "$new_recover_file"
    echo "No Recover image was built!"
    echo
fi
[ "$BUILDRECOVER" = "y" ] && exit 0
echo "All done, Press 'ENTER' to finish"
while !(read -s);do
	sleep 1
done
exit 0
