#!/bin/bash
echo "-------------------------------------------------------------------------------------------------------------"
echo
if [ `id -u` -eq 0 ]; then
 clear
  echo
  echo "This script needs to be executed without 'su' privileges."
  echo "Login as normal user!"
  echo "Speed-to-fritz must be run as normal user as well!" 
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  sleep 10
  exit 0
fi
KEY="x"
#while [ "$KEY" != "y" ]; do
 echo
 echo "The update and install procedure has to be repeated until all errors are gone!"
 echo
 echo -n "   Do an update and installation of missing system tools? (y/n)? "; read -n 1 -s YESNO; echo
 [ "$YESNO" = "n" ] &&  KEY="y"
 [ "$YESNO" = "n" ] || [ "$YESNO" = "y" ] || echo "wrong key!"
if [ "$YESNO" = "y" ]; then
 echo "Update ----->"
 sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade &&\
 sudo apt-get -y install gcc g++ binutils autoconf automake automake1.9
 sudo apt-get -y update && sudo apt-get -y upgrade &&\
 sudo apt-get -y install libtool make libncurses5-dev zlib1g-dev flex bison patch texinfo
 sudo apt-get -y update && sudo apt-get -y upgrade &&\
 sudo apt-get -y install tofrodos gettext jam pkg-config jikes fastjar realpath perl
 sudo apt-get -y update && sudo apt-get -y upgrade &&\
 sudo apt-get -y install libstring-crc32-perl ruby ruby1.8 gawk python subversion bzip2
 echo "End update <-----"
fi
#done
echo "-------------------------------------------------------------------------------------------------------------"
echo "Install tools ..." 
echo 
echo 

make toolsdirclean
#dont do 'svn co' or 'or svn up'  because ./tools/config is from a different source!"
#and some changes are also made to the sources especially concerning ./tools/config
#svn co http://svn.freetz.org/trunk/tools tools -r 2367 (used up to 31.12.2008)
#svn co http://svn.freetz.org/trunk/tools tools -r 2944
#revision update done, Makefile is different to Freetz, only tools/make dir is used.
#svn up
make tools
echo "Installation finshed!"
sleep 10
