#!/bin/bash
# On some systems this tools are missing. They are in use with menuconfig
# They only need to be installed once, you may remove the apt-get line for repeated use
echo "----------------------------------------------------------------------------------------------"
echo "----------------------------------------------------------------------------------------------"
echo "Attempt to update some tools, this only works on Debian, Ubunto ..."
echo "----------------------------------------------------------------------------------------------"
echo "On some systems even sudo must be installed first, see Wiki for andLINUX   ..."
echo "If sudo is missing, do the following:"
echo "apt-get install sudo (as root)"
echo "Setup a new user and insert this new users to /etc/sudoers with visudo" 
echo "Der erstellte neue Benutzer muss aber noch in /etc/sudoers, eingetragen werden."
echo "Das File /etc/sudoers mit visudo oeffnen, und die folgende Zeile anhaengen, "
echo "wobei 'newusername' fuer den neu angelegten Benutzernamen steht."
echo "(Dazu visudo [Enter] newusername ALL=(ALL) ALL als letzte Zeile eintippen, Strg O [Enter], Strg X)"
echo "freetz ALL=(ALL) ALL "
echo "----------------------------------------------------------------------------------------------"
sudo apt-get -qqyf install build-essential  
sudo apt-get -qqyf install libncurses5-dev
sudo apt-get -qqyf install automake
sudo apt-get -qqyf install patch
sudo apt-get -qqyf install subversion
sudo apt-get -qqyf install ftp
echo "----------------------------------------------------------------------------------------------"
. ./start
