#!/bin/bash
echo
echo "********************************************************************************"
echo
if [ -e ./Firmware.conf.tar ]; then
    echo "Extract Firmware.conf from ./Firmware.conf.tar and start speed-to-fritz with:" && sleep 1
    tar xfv ./Firmware.conf.tar
    ./add_ll.sh
    ./sp-to-fritz.sh -z -c Firmware.conf
else
    echo "./Firmware.conf.tar not found" && sleep 5 && echo "********************************************************************************"
fi