#!/bin/bash
#KernelVersion="2.6.19.2"
echo "********************************************************************************"
echo -e "\033[1mPhase 4:\033[0m Apply changes."
echo "********************************************************************************"
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# only executed if productname is changed
if [ ! -e "${SRC}"/etc/default.${CONFIG_PRODUKT} ]; then
echo -e "\033[1m${SORCE_PRODUKT}  --->   ${CONFIG_PRODUKT}\033[0m "
 echo2 "-- Move contents of OEM directory:"
 echo2 "      move /etc/default.${SORCE_PRODUKT} --> /etc/default.${CONFIG_PRODUKT}"
    mkdir -m 755 "${SRC}/etc/default.${CONFIG_PRODUKT}"
   "$TAR" -c -C "${SRC}/etc/default.${SORCE_PRODUKT}" . | "$TAR" -x -C "${SRC}/etc/default.${CONFIG_PRODUKT}"
    rm -fdr "${SRC}"/etc/default.${SORCE_PRODUKT}
fi

rm -f "${SRC}"/lib/modules/micro*
rm -f "${SRC}"/lib/modules/dect*
rm -f "${SRC}"/usr/bin/dect*
rm -f "${SRC}"/usr/bin/usb*
rm -f "${SRC}"/bin/usb*
# pcmlink boot error, da modul nicht kompatibel ist
rm -f "${SRC}"/lib/modules/c55*

cp -fdrp "${DST}"/lib/modules/bitfile* --target-directory="${SRC}"/lib/modules &&\

if [ ${ATA_ONLY} = "n" ]; then
 #annex B driver
 mkdir -p ./addon/tmp/modules/dsp_ur8
 if [ -d "${SRC}/lib/modules/dsp_ur8"  ]; then
  [ ${SAVE_AVM_DSL} = "y" ] && [ -f "${SRC}/lib/modules/dsp_ur8/ur8-B-dsl.bin"  ] && cp -fdrp "${SRC}"/lib/modules/dsp_ur8/ur8-B-dsl.bin --target-directory=./addon/tmp/modules/dsp_ur8 &&\
  echo "  -- AVM DSL Annex B Driver saved to: ./addon/tmp/modules!"
  [ ${SAVE_SRC2_DSL} = "y" ] && [ -f "${SRC_2}/lib/modules/dsp_ur8/ur8-B-dsl.bin"  ] && cp -fdrp "${SRC_2}"/lib/modules/dsp_ur8/ur8-B-dsl.bin --target-directory=./addon/tmp/modules/dsp_ur8 &&\
  echo "  -- AVM DSL Annex B Driver saved to: ./addon/tmp/modules!"
  [ ${USE_OWN_DSL} = "y" ] && [ -f "./addon/tmp/modules/dsp_ur8/ur8-B-dsl.bin"  ] && cp -fdrp ./addon/tmp/modules/dsp_ur8/ur8-B-dsl.bin --target-directory="${SRC}"/lib/modules/dsp_ur8 &&\
  echo "  -- DSL Annex B Driver was taken from local directory ./addon/tmp/modules!"
  [ ${USE_SRC2_DSL} = "y" ] && [ -f "${SRC_2}/lib/modules/dsp_ur8/ur8-B-dsl.bin"  ] && cp -fdrp "${SRC_2}"/lib/modules/dsp_ur8/ur8-B-dsl.bin --target-directory="${SRC}"/lib/modules/dsp_ur8 &&\
  echo "  -- DSL Annex B Driver was taken from ${SORCE_2_PRODUKT}!" 
  #annex A driver
  [ ${SAVE_AVM_DSL} = "y" ] && [ -f "${SRC}/lib/modules/dsp_ur8/ur8-A-dsl.bin"  ] && cp -fdrp "${SRC}"/lib/modules/dsp_ur8/ur8-A-dsl.bin --target-directory=./addon/tmp/modules/dsp_ur8 &&\
  echo "  -- AVM DSL Annex A Driver saved to: ./addon/tmp/modules!"
  [ ${SAVE_SRC2_DSL} = "y" ] && [ -f "${SRC_2}/lib/modules/dsp_ur8/ur8-A-dsl.bin"  ] && cp -fdrp "${SRC_2}"/lib/modules/dsp_ur8/ur8-A-dsl.bin --target-directory=./addon/tmp/modules/dsp_ur8 &&\
  echo "  -- AVM DSL Annex A Driver saved to: ./addon/tmp/modules!"
  [ ${USE_OWN_DSL} = "y" ] && [ -f "./addon/tmp/modules/dsp_ur8/ur8-A-dsl.bin"  ] && cp -fdrp ./addon/tmp/modules/dsp_ur8/ur8-A-dsl.bin --target-directory="${SRC}"/lib/modules/dsp_ur8 &&\
  echo "  -- DSL Annex A Driver was taken from local directory ./addon/tmp/modules!"
  [ ${USE_SRC2_DSL} = "y" ] && [ -f "${SRC_2}/lib/modules/dsp_ur8/ur8-A-dsl.bin"  ] && cp -fdrp "${SRC_2}"/lib/modules/dsp_ur8/ur8-A-dsl.bin --target-directory="${SRC}"/lib/modules/dsp_ur8 &&\
  echo "  -- DSL Annex A Driver was taken from ${SORCE_2_PRODUKT}!" 
 fi
 #save space on 8MB boxes specially
 [ "${REMOVE_ANNEX_B_DSL_DRIVER}" = "y" ] && [ -f "${SRC}/lib/modules/dsp_ur8/ur8-B-dsl.bin" ] && rm -f "${SRC}"/lib/modules/dsp_ur8/ur8-B-dsl.bin &&\
 echo "  -- DSL Annex B Driver was removed from ${SORCE_PRODUKT}!"
 #save space on 8MB boxes specially
 [ "${REMOVE_ANNEX_A_DSL_DRIVER}" = "y" ] && [ -f "${SRC}/lib/modules/dsp_ur8/ur8-A-dsl.bin" ] && rm -f "${SRC}"/lib/modules/dsp_ur8/ur8-A-dsl.bin &&\
 echo "  -- DSL Annex A Driver was removed from ${SORCE_PRODUKT}!"
else
#remove ADSL
#dont start dsl
sed -i -e 's|/etc/init.d/rc.dsl.sh start||' "${SRC}/etc/init.d/rc.S" 
rm -fdr "${SRC}"/lib/modules/dsp_ur8
#<-- ATA only
fi

#echo "-- Matching Versions: $AVM_VERSION-$AVM_SUBVERSION - $TCOM_VERSION-$TCOM_SUBVERSION"
[ ${FORCE_TCOM_PIGLET} = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/char --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers &&\
echo "  -- Piglet driver was taken from t-com Firmware!" 
#Fon Driver
[ ${FORCE_TCOM_FON} = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/isdn --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers &&\
echo "  -- Fon driver was taken from t-com Firmware!" 


#copy wlan config
cp -fdrp "${DST}"/etc/init.d/rc.wlan --target-directory="${SRC}"/etc/init.d

#copy all modules
#cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel

#cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/userman --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers
#cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/dsld --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers
#cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/dsl --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers
cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/char --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers
cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/isdn --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers
# wlan bracht t-com kernel
#[ ${XCHANGE_KERNEL} = "y" ] && 

cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/net --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers
# &&\
#echo "  -- Wlan driver was taken from t-com Firmware!" 
###cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/usb --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers
###cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/scsi --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers
###cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/net/sched --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/net

rm -fdr "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/usb
rm -fdr "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/scsi
rm -fdr "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/isdn/avm_dect
rm -fdr "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/char/dect_io

#adapt parameters for Piglet bitfile to be

sed -i -e 's/Fritz_Box_7270/Fritz_Box_W503/' "${SRC}/etc/init.d/rc.S"
sed -i -e 's/microvoip_isdn_top.bit/bitfile_isdn.bit/' "${SRC}/etc/init.d/rc.S"
sed -i -e "/piglet_load_params=\"/,/dect_secondlevelfile/d" "${SRC}/etc/init.d/rc.S"
sed -i -e "/dectfw_firstlevel.hex/,/dectfw_secondlevel.hex/d" "${SRC}/etc/init.d/rc.S"
sed -i -e 's/piglet_bitfile=$piglet_bitfile/piglet_bitfile=$piglet_bitfile piglet_potsbitfile=$piglet_potsbitfile /' "${SRC}/etc/init.d/rc.S"

sed -i -e '/piglet_bitfile=/a \
piglet_potsbitfile=/lib/modules/bitfile_pots.bit${HWRevision_BitFileCount}\
piglet_bitfilemode=\`/bin/testvalue /var/flash/telefon_misc 4 2638\`\
if [ -z $piglet_bitfilemode ] ; then piglet_bitfilemode=0 ; fi\
echo PigletMode: $piglet_bitfilemode\
piglet_load_params="\\\
piglet_enable_button=3 \\\
piglet_bitfilemode=$piglet_bitfilemode \\\
piglet_use_pll3_clk=1 \\\
"\
modprobe Piglet_noemif piglet_bitfile=$piglet_bitfile piglet_potsbitfile=$piglet_potsbitfile $piglet_load_params' "${SRC}/etc/init.d/rc.S"
#rmove dect dev
#mknod /var/flash/dect_misc c $tffs_major $((0xB0))
#mknod /var/flash/dect_eeprom c $tffs_major $((0xB1))
#mknod /var/flash/dmgr_handset_user c $tffs_major $((0xB2))

sed -i -e "/dect_misc/,/dmgr_handset_user/d" "${SRC}/etc/init.d/rc.S"

#remove USB config
sed -i -e "/#### USB-Host Config ####/,/#### USB-Client Config ####/d" "${SRC}/etc/init.d/rc.S"
#remove DECT config
sed -i -e "s/copy_dect_defaults()/copy_dect()/" "${SRC}/etc/init.d/rc.S"
sed -i -e "/copy_dect_defaults/d" "${SRC}/etc/init.d/rc.S"
sed -i -e "/modprobe dect_io/d" "${SRC}/etc/init.d/rc.S"

#watchdog
#sed -i -e "s/init-start 120/init-start 240/" "${SRC}/etc/init.d/rc.S"

#dont start mediaserver
sed -i -e "/rc.media start/d" "${SRC}/etc/init.d/rc.S"

sed -i -e '/## cleanup - if running, stop debug/i \
## change to external SYNC for TE-Mode\
#########################################################################\
echo isdn_reg 8 0 >\/dev\/debug\
#########################################################################' "${SRC}/etc/init.d/rc.S"



#Testvariante!!
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#cp -fdrp "${DST}"/etc/init.d/rc.S --target-directory="${SRC}"/etc/init.d


# disable plugin
rm -f "${SRC}/sbin/start_plugin.sh"
sed -i -e "/check-plugins/d" "${SRC}/etc/init.d/rc.S"

#workaround for HWRevision
if [ -f "${SRC}/sbin/start_plugin.sh" ]; then
sed -i -e "/url=\"\`\/sbin\/pluginurl\`\"/i\
	export HWRevision=\"$FBHWRevision\"" "${SRC}/sbin/start_plugin.sh"
sed -i -e "/url=\"\`\/sbin\/pluginurl\`\"/a\
	export HWRevision=\"$HWID\"" "${SRC}/sbin/start_plugin.sh"
fi
sed -i -e "s|hardware=\${HWRevision}|hardware=${FBHWRevision}|" "${SRC}/etc/init.d/rc.conf"

#tests 
sed -i -e '/export ANNEX_TEST/a\
if [ "$STATUS_TEST" != "0" ]; then\
/usr/bin/dsl_info.sh /&\
fi' "${SRC}/etc/init.d/rc.S" 


#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#copy second source internet dsl menue
[ ${USE_SOURCE2_DSLMNUE} = "y" ] && $sh2_DIR/copy_dsl_tab_pages_SRC2 "${SRC}" "${SRC_2}" "${OEMLIST}"
 echo2 "New WEB GUI will be modified"
#use scond source web GUI
[ ${USE_SOURCE2_WEBMNUE} = "y" ] && $sh2_DIR/copy_www_SRC2 "${SRC}" "${SRC_2}" "${OEMLINK}"

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#$sh_DIR/patch_leddef_W503.sh "${SRC}" "${DST}"
# set led definition 
if [ -f "${DST}"/lib/modules/$KernelVersion/kernel/drivers/char/led_module.ko ] && [ "${FORCE_TCOM_LEDDRIVER}" = "y" ]; then
    cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/char/led_module.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/char
    cp -fdrp "${DST}"/lib/libled* --target-directory="${SRC}"/lib
    cp -fdrp "${DST}"/bin/led* --target-directory="${SRC}"/bin
    cp -fr "${DST}"/bin/update_led_on ${SRC}/bin/update_led_on
    cp -fr "${DST}"/bin/update_led_off ${SRC}/bin/update_led_off
    echo "  -- LED Driver was taken from the original t-com firmware"
fi
if [ -f "${SRC_2}"/lib/modules/$KernelVersion/kernel/drivers/char/led_module.ko ] && [ "${FORCE_SRC2_LEDDRIVER}" = "y" ]; then
    cp -fdrp "${SRC_2}"/lib/modules/$KernelVersion/kernel/drivers/char/led_module.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/char
    cp -fdrp "${SRC_2}"/lib/libled* --target-directory="${SRC}"/lib
    cp -fdrp "${SRC_2}"/bin/led* --target-directory="${SRC}"/bin
    cp -fr "${SRC_2}"/bin/update_led_on ${SRC}/bin/update_led_on
    cp -fr "${SRC_2}"/bin/update_led_off ${SRC}/bin/update_led_off
    echo "  -- LED Driver was taken from AVM source 2 firmware"
fi
# 503 
$sh_DIR/patch_config_rc.conf.sh "${SRC}" "${DST}" 503
#remove FON3 menus
[ ${REMOVE_MENU_ITEM} = "y" ] && $sh_DIR/rmv_menus.sh "${SRC}" "${FBMOD}"

#Add buchsend button to fon bookpage
[ "${ADD_PHONESEND}" = "y" ] && $sh_DIR/patch_fonbuch.sh "${SRC}"

# skripts for startig ftp on USB
cp -fdpr  ./addon/tmp/jp   --target-directory="${SRC}"
#Annex A is not usable up to now
#patch annex parameter
$sh_DIR/patch_annex.sh "${SRC}"
# add kapselung and annex settings page if missing
$sh_DIR/add_multi_settings.sh
#remove kids and help
[ ${REMOVE_KIDS} = "y" ] && $sh_DIR/rmv_kids.sh "${SRC}"
[ ${REMOVE_HELP} = "y" ] && $sh_DIR/rmv_help.sh "${SRC}"

echo "********************************************************************************"

#/var/flash/fx_def