#!/bin/bash
#KernelVersion="2.6.19.2"
echo "********************************************************************************"
echo -e "\033[1mPhase 4:\033[0m Apply changes."
echo "********************************************************************************"
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# only executed if productname is changed
if [ ! -e "${SRC}"/etc/default.${CONFIG_PRODUKT} ]; then
echo -e "\033[1m${SORCE_PRODUKT}  --->   ${CONFIG_PRODUKT}\033[0m "
 echo2 "-- Move contents of OEM directory:"
 echo2 "      move /etc/default.${SORCE_PRODUKT} --> /etc/default.${CONFIG_PRODUKT}"
    mkdir -m 755 "${SRC}/etc/default.${CONFIG_PRODUKT}"
   "$TAR" -c -C "${SRC}/etc/default.${SORCE_PRODUKT}" . | "$TAR" -x -C "${SRC}/etc/default.${CONFIG_PRODUKT}"
    rm -fdr "${SRC}"/etc/default.${SORCE_PRODUKT}
fi
#ATA only--->
if [ ${ATA_ONLY} = "n" ]; then
#add DSL driver depending on the settings made

# "vinax_fw_adsl.bin" "vinax_fw_vdsl.bin"
#remove 7270 DSL 

rm -fdr "${SRC}"/lib/modules/dsp_ur8
rm -fdr "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/dsl
#/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko:

#sed -i -e 's|/dsl/dsl_ur8.ko|/vinax/drv_vinax.ko|' "${SRC}"/lib/modules/$KernelVersion/modules.dep
echo "/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko:" >>"${SRC}"/lib/modules/$KernelVersion/modules.dep

# "vinax_driver"  
#Attention! Vinax uses aditional /dev/vinax device entrys the are generateed via /tools/device_table.txt (makedevice option)
[ ${FAKEROOT_ON} = "n" ] && cp -fdrp "${DST}"/dev/vinax --target-directory="${SRC}"/dev #this copy is onliy usable if run as root

mkdir "${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax
cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax
[ "${FORCE_TCOM_KDSLDMOD}" = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/dsld/kdsldmod.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/dsld
cp -fdrp "${DST}"/lib/modules/$KernelVersion/modules.symbols --target-directory="${SRC}"/lib/modules/$KernelVersion
cp -fdrp "${DST}"/usr/sbin --target-directory="${SRC}"/usr
cp -fdrp "${DST}"/lib/modules/vinax_fw_vdsl.bin --target-directory="${SRC}"/lib/modules
cp -fdrp "${DST}"/lib/modules/vinax_fw_adsl.bin --target-directory="${SRC}"/lib/modules &&\
echo "  -- DSL Driver was taken from the original t-com firmware!"
#not needed as far, because /bin/ctlmgr is not compatibel, looks like this is the reason wy not all is configurabe concerning ATM and ADSL via GUI
[ -f "${SRC}"/usr/share/ctlmgr/libvdsl.so ] || cp -fdrp "${DST}"/usr/share/ctlmgr/libvdsl.so --target-directory="${SRC}"/usr/share/ctlmgr

if [ ${SAVE_TCOM_DSL} = "y" ]; then
    cp -fdrp "${DST}"/lib/modules/vinax* --target-directory=./addon/tmp/W920/squashfs-root/lib/modules &&\
    echo "  -- TCOM DSL Driver saved to: ./addon/tmp/W920!"
    cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko --target-directory=./addon/tmp/W920/squashfs-root/lib/modules/$KernelVersion/kernel/drivers/vinax
    cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/dsld/kdsldmod.ko --target-directory=./addon/tmp/W920/squashfs-root/lib/modules/$KernelVersion/kernel/drivers/dsld
    cp -fdrp "${DST}"/lib/modules/$KernelVersion/modules.symbols --target-directory=./addon/tmp/W920/squashfs-root/lib/modules/$KernelVersion
    cp -fdrp "${DST}"/usr/sbin --target-directory=./addon/tmp/W920/squashfs-root/usr
fi

if [ ${SAVE_SRC2_DSL} = "y" ]; then
    cp -fdrp "${SRC_2}"/lib/modules/vinax* --target-directory=./addon/tmp/W920 &&\
    echo "  -- AVM DSL Driver saved to: ./addon/tmp/W920!"
    cp -fdrp "${SRC_2}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko --target-directory=./addon/tmp/W920/squashfs-root/lib/modules/$KernelVersion/kernel/drivers/vinax
    cp -fdrp "${SRC_2}"/lib/modules/$KernelVersion/kernel/drivers/dsld/kdsldmod.ko --target-directory=./addon/tmp/W920/squashfs-root/lib/modules/$KernelVersion/kernel/drivers/dsld
    cp -fdrp "${SRC_2}"/lib/modules/$KernelVersion/modules.symbols --target-directory=./addon/tmp/W920/squashfs-root/lib/modules/$KernelVersion
    cp -fdrp "${SRC_2}"/usr/sbin --target-directory=./addon/tmp/W920/squashfs-root/usr
fi

if [ ${USE_SRC2_DSL} = "y" ]; then
    cp -fdrp "${SRC_2}"/lib/modules/$KernelVersion/kernel/drivers/vinax/drv_vinax.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/vinax
    [ "${FORCE_TCOM_KDSLDMOD}" = "y" ] || cp -fdrp "${SRC_2}"/lib/modules/$KernelVersion/kernel/drivers/dsld/kdsldmod.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/dsld
    cp -fdrp "${SRC_2}"/lib/modules/$KernelVersion/modules.symbols --target-directory="${SRC}"/lib/modules/$KernelVersion
    cp -fdrp "${SRC_2}"/usr/sbin --target-directory="${SRC}"/usr
    cp -fdrp "${SRC_2}"/lib/modules/vinax_fw_vdsl.bin --target-directory="${SRC}"/lib/modules
    cp -fdrp "${SRC_2}"/lib/modules/vinax_fw_adsl.bin --target-directory="${SRC}"/lib/modules &&\
    echo "  -- DSL Driver was taken from the original t-com firmware!"
fi
 
[ ${USE_OWN_DSL} = "y" ] && cp -fdrp ./addon/tmp/W920/squashfs-root/* --target-directory="${SRC}" &&\
echo "  -- DSL Driver was taken from local directory ./addon/tmp/W920!"

#add one entry in module
sed -i -e '/alias symbol:scsi_mode_sense scsi_mod/a\
alias symbol:PCMRoute_RefreshTimeslot pcmlink' "${SRC}"/lib/modules/$KernelVersion/modules.symbols

#DSL skripts--->
#copy VDSL Skript
cp -fdpr  "${DST}"/etc/init.d/rc.vdsl.sh  --target-directory="${SRC}"/etc/init.d
#include vdsl skript
sed -i -e 's|/etc/init.d/rc.dsl.sh start|\. /etc/init.d/rc.vdsl.sh|' "${SRC}/etc/init.d/rc.S" 

#Annex A not working up to now  
sed -i -e "s/DSL_Mode=\"VB\"/DSL_Mode=\"V$ANNEX\"/" "${SRC}/etc/init.d/rc.vdsl.sh" 
#sed -i -e "s/annex=B/annex=$ANNEX/" "${SRC}/etc/init.d/rc.dsl.sh" 

#ATM Parameter
sed -i -e "s/dsl_pipe sarcs 0 0 0 1 32 1/dsl_pipe sarcs 0 0 0 $VPI $VCI $KAPSELUNG/" "${SRC}/etc/init.d/rc.vdsl.sh" 
sed -i -e "s/dsl_pipe sarrts 0 0 1 1 32/dsl_pipe sarrts 0 0 1 $VPI $VCI/" "${SRC}/etc/init.d/rc.vdsl.sh" 

#diffence in rc.dsl.sh  
sed -i -e 's|dsl_ur8|tiatm|' "${SRC}/etc/init.d/rc.dsl.sh"
sed -i -e '/modprobe tiatm/a\
echo "MODE = vdsl" > \/dev\/avm_power' "${SRC}/etc/init.d/rc.dsl.sh"

#dont think it is needed, but for safty
sed -i -e '/CONFIG_VDSL=/a\
export CONFIG_VINAX="y"' "${SRC}/etc/init.d/rc.conf" 
#<---DSL skripts
else

#remove ADSL
#dont start dsl
sed -i -e 's|/etc/init.d/rc.dsl.sh start||' "${SRC}/etc/init.d/rc.S" 
rm -fdr "${SRC}"/lib/modules/dsp_ur8
#<-- ATA only
fi
#VDSL would not start if wrong HWrevision is in use, so it only can be set in ATA mod
#But pluginsupport needs AVM HWrevision to setup the download URL for plugins 
#workaround for HWRevision
if [ -f "${SRC}/sbin/start_plugin.sh" ]; then
sed -i -e "/        url=\"\`\/sbin\/pluginurl\`\"/i\
	export HWRevision=\"$FB_HWRevision\"" "${SRC}/sbin/start_plugin.sh"
sed -i -e "/        url=\"\`\/sbin\/pluginurl\`\"/a\
	export HWRevision=\"$HWID\"" "${SRC}/sbin/start_plugin.sh"
fi

#tests 
sed -i -e '/export ANNEX_TEST/a\
if [ "$STATUS_TEST" != "0" ]; then\
/usr/bin/dsl_info.sh /&\
fi' "${SRC}/etc/init.d/rc.S" 


#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo "-- Matching Versions: $AVM_VERSION-$AVM_SUBVERSION - $TCOM_VERSION-$TCOM_SUBVERSION"
[ ${FORCE_TCOM_PIGLET} = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/char/Piglet_noemif/Piglet_noemif.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/char/Piglet_noemif
#Fon Driver
[ ${FORCE_TCOM_FON} = "y" ] && cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/isdn/isdn_fon5/zzz/* --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/isdn/isdn_fon5/zzz
#xilix W920 Driver must be for the hardware in use
cp -fdrp "${DST}"/lib/modules/microvoip_isdn_top.bit --target-directory="${SRC}"/lib/modules

#copy second source internet dsl menue
[ ${USE_SOURCE2_DSLMNUE} = "y" ] && $sh2_DIR/copy_dsl_tab_pages_SRC2 "${SRC}" "${SRC_2}" "${OEMLIST}"
 echo2 "New WEB GUI will be modified"
#use scond source web GUI
[ ${USE_SOURCE2_WEBMNUE} = "y" ] && $sh2_DIR/copy_www_SRC2 "${SRC}" "${SRC_2}" "${OEMLINK}"
#Annex A is not usable up to now
#patch annex Fom parameter
$sh_DIR/patch_annex.sh "${SRC}"

#enable button
sed -i -e 's/piglet_enable_button=2/piglet_enable_button=3/' "${SRC}/etc/init.d/rc.S" 
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# set led definition 
if [ -f "${DST}"/lib/modules/$KernelVersion/kernel/drivers/char/led_module.ko ] && [ ${FORCE_TCOM_LEDDRIVER} = "y" ]; then
    cp -fdrp "${DST}"/lib/modules/$KernelVersion/kernel/drivers/char/led_module.ko --target-directory="${SRC}"/lib/modules/$KernelVersion/kernel/drivers/char
    cp -fdrp "${DST}"/lib/libled* --target-directory="${SRC}"/lib
    cp -fdrp "${DST}"/bin/led* --target-directory="${SRC}"/bin
    cp -fr "${DST}"/bin/update_led_on ${SRC}/bin/update_led_on
    cp -fr "${DST}"/bin/update_led_off ${SRC}/bin/update_led_off
    echo "  -- LED Driver was taken from the original t-com firmware!"
fi
$sh_DIR/patch_leddef_7270.sh "${SRC}" "${DST}"
# add missing gifs
$sh_DIR/add_vdslscale.sh "${SRC}" "${OEMLIST}"
# 920 
$sh_DIR/patch_config_rc.conf.sh "${SRC}" "${DST}" 920
#remove FON3 menus
[ ${REMOVE_MENU_ITEM} = "y" ] && $sh_DIR/rmv_menus.sh "${SRC}" "${FBMOD}"

#Add buchsend button to fon bookpage
$sh_DIR/patch_fonbuch.sh "${SRC}"

# skripts for startig ftp on USB
cp -fdpr  ./addon/tmp/jp   --target-directory="${SRC}"

echo "********************************************************************************"

