#!/bin/bash
echo "********************************************************************************"
echo -e "\033[1mPhase 4:\033[0m Apply changes."
echo "********************************************************************************"
echo "-- Matching Versions: $AVM_VERSION-$AVM_SUBVERSION - $TCOM_VERSION-$TCOM_SUBVERSION"
echo "Replacing hardware related files of AVM firmware images ..."
echo2 "-- Copy original AVM module:"
echo2 "      /lib/modules"


if [ ${ATA_ONLY} = "n" ]; then
#add DSL driver dependig on the settings made in firmware.conf707
[ ${SAVE_AVM_DSL} = "y" ] && cp -fdrp "${SRC}"/lib/modules/microvoip-dsl*.bin --target-directory=./addon/tmp/modules &&\
echo "  -- AVM DSL Driver saved to: ./addon/tmp/modules!"
[ ${SAVE_SRC2_DSL} = "y" ] && cp -fdrp "${SRC_2}"/lib/modules/microvoip-dsl*.bin --target-directory=./addon/tmp/modules &&\
echo "  -- AVM DSL Driver saved to: ./addon/tmp/modules!"
[ ${USE_OWN_DSL} = "y" ] && cp -fdrp ./addon/tmp/modules/microvoip-dsl*.bin --target-directory="${SRC}"/lib/modules &&\
echo "  -- DSL Driver was taken from local directory ./addon/tmp/modules!"
[ ${USE_SRC2_DSL} = "y" ] && cp -fdrp "${SRC_2}"/lib/modules/microvoip-dsl*.bin --target-directory="${SRC}"/lib/modules &&\
echo "  -- DSL Driver was taken from ${SORCE_2_PRODUKT}!" 
else
#remove ADSL
#dont start dsl
sed -i -e 's|/etc/init.d/rc.dsl.sh start||' "${SRC}/etc/init.d/rc.S" 
rm -fdr "${SRC}"/lib/modules/dsp_ur8
rm -f "${SRC}"/lib/modules/microvoip-dsl*.bin
#<-- ATA only
fi

#copy second source www dir
[ ${USE_SOURCE2_WEBMNUE} = "y" ] && $sh2_DIR/copy_www_SRC2 "${SRC}" "${SRC_2}" "${OEMLINK}"
[ ${USE_SOURCE2_WEBMNUE} = "y" ] && . $inc_DIR/get_SRC2_ver 

#copy second source internet dsl menue
[ ${USE_SOURCE2_DSLMNUE} = "y" ] && $sh2_DIR/copy_dsl_tab_pages_SRC2 "${SRC}" "${SRC_2}" "${OEMLINK}"

echo2 "-- copy complete AVM source to destination directory!"

#patch annex parameter
$sh_DIR/patch_annex.sh "${SRC}"


echo "********************************************************************************"
sleep 10